## LOGISTIC REGRESSION (LR): 

C is [REGULARIZATION PARAMETER]

Logistic Regression used in binary classification & multiple but best in binary classification.



In [1]:
from sklearn import datasets
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import accuracy_score

## LOAD THE DATA:

In [2]:
iris=datasets.load_iris()

In [3]:
iris

{'data': array([[5.1, 3.5, 1.4, 0.2],
        [4.9, 3. , 1.4, 0.2],
        [4.7, 3.2, 1.3, 0.2],
        [4.6, 3.1, 1.5, 0.2],
        [5. , 3.6, 1.4, 0.2],
        [5.4, 3.9, 1.7, 0.4],
        [4.6, 3.4, 1.4, 0.3],
        [5. , 3.4, 1.5, 0.2],
        [4.4, 2.9, 1.4, 0.2],
        [4.9, 3.1, 1.5, 0.1],
        [5.4, 3.7, 1.5, 0.2],
        [4.8, 3.4, 1.6, 0.2],
        [4.8, 3. , 1.4, 0.1],
        [4.3, 3. , 1.1, 0.1],
        [5.8, 4. , 1.2, 0.2],
        [5.7, 4.4, 1.5, 0.4],
        [5.4, 3.9, 1.3, 0.4],
        [5.1, 3.5, 1.4, 0.3],
        [5.7, 3.8, 1.7, 0.3],
        [5.1, 3.8, 1.5, 0.3],
        [5.4, 3.4, 1.7, 0.2],
        [5.1, 3.7, 1.5, 0.4],
        [4.6, 3.6, 1. , 0.2],
        [5.1, 3.3, 1.7, 0.5],
        [4.8, 3.4, 1.9, 0.2],
        [5. , 3. , 1.6, 0.2],
        [5. , 3.4, 1.6, 0.4],
        [5.2, 3.5, 1.5, 0.2],
        [5.2, 3.4, 1.4, 0.2],
        [4.7, 3.2, 1.6, 0.2],
        [4.8, 3.1, 1.6, 0.2],
        [5.4, 3.4, 1.5, 0.4],
        [5.2, 4.1, 1.5, 0.1],
  

## Get the Features & labels from the Data:

In [13]:
x=iris.data
y=iris.target

In [14]:
x

array([[5.1, 3.5, 1.4, 0.2],
       [4.9, 3. , 1.4, 0.2],
       [4.7, 3.2, 1.3, 0.2],
       [4.6, 3.1, 1.5, 0.2],
       [5. , 3.6, 1.4, 0.2],
       [5.4, 3.9, 1.7, 0.4],
       [4.6, 3.4, 1.4, 0.3],
       [5. , 3.4, 1.5, 0.2],
       [4.4, 2.9, 1.4, 0.2],
       [4.9, 3.1, 1.5, 0.1],
       [5.4, 3.7, 1.5, 0.2],
       [4.8, 3.4, 1.6, 0.2],
       [4.8, 3. , 1.4, 0.1],
       [4.3, 3. , 1.1, 0.1],
       [5.8, 4. , 1.2, 0.2],
       [5.7, 4.4, 1.5, 0.4],
       [5.4, 3.9, 1.3, 0.4],
       [5.1, 3.5, 1.4, 0.3],
       [5.7, 3.8, 1.7, 0.3],
       [5.1, 3.8, 1.5, 0.3],
       [5.4, 3.4, 1.7, 0.2],
       [5.1, 3.7, 1.5, 0.4],
       [4.6, 3.6, 1. , 0.2],
       [5.1, 3.3, 1.7, 0.5],
       [4.8, 3.4, 1.9, 0.2],
       [5. , 3. , 1.6, 0.2],
       [5. , 3.4, 1.6, 0.4],
       [5.2, 3.5, 1.5, 0.2],
       [5.2, 3.4, 1.4, 0.2],
       [4.7, 3.2, 1.6, 0.2],
       [4.8, 3.1, 1.6, 0.2],
       [5.4, 3.4, 1.5, 0.4],
       [5.2, 4.1, 1.5, 0.1],
       [5.5, 4.2, 1.4, 0.2],
       [4.9, 3

In [15]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

## Split into train and test:

In [16]:
x_train,x_test,y_train,y_test=train_test_split(x,y,test_size=0.5,random_state=0)

## Standardize the data: 

In [17]:
sc=StandardScaler()
x_train_std=sc.fit_transform(x_train)
x_test_std=sc.fit_transform(x_test) 

In [18]:
x_train_std

array([[-1.37188119,  0.01594752, -1.13425915, -1.17406582],
       [ 0.04805953, -0.22326533,  0.75267844,  0.76653884],
       [-0.82575014, -1.41932957, -0.34803516, -0.0824757 ],
       [-1.37188119,  0.73358607, -1.18667408, -1.05277803],
       [ 0.37573816, -2.13696812,  0.43818884,  0.40267547],
       [ 1.46800026,  1.21201177,  1.27682777,  1.61555338],
       [-0.17039289, -0.46247818,  0.28094404,  0.16009988],
       [-1.15342877, -0.22326533, -1.18667408, -1.29535361],
       [ 1.35877405, -0.22326533,  1.1719979 ,  1.13040221],
       [ 1.14032163,  0.25516037,  1.06716804,  1.37297779],
       [ 0.70341679, -0.22326533,  1.11958297,  1.25169   ],
       [ 0.59419058, -0.70169103,  1.0147531 ,  1.13040221],
       [-0.82575014,  1.69043747, -1.08184422, -1.17406582],
       [-1.15342877,  0.73358607, -1.08184422, -1.17406582],
       [ 0.70341679,  0.25516037,  0.75267844,  1.00911442],
       [ 0.92186921,  0.49437322,  1.06716804,  1.13040221],
       [-1.4811074 , -1.

In [19]:
x_test_std

array([[-0.04237546, -0.49481962,  0.78407966,  1.70108248],
       [ 0.23398623, -1.83619812,  0.09298381, -0.33556131],
       [-0.45691799,  2.63506354, -1.54051549, -1.49935777],
       [ 2.0303372 , -0.27125654,  1.53800241,  0.82823514],
       [-1.14782221,  0.84655887, -1.47768859, -1.49935777],
       [ 0.64852876,  0.62299579,  1.34952172,  1.84655704],
       [-1.14782221,  1.07012196, -1.60334238, -1.35388321],
       [ 1.20125214,  0.17586963,  0.53277208,  0.39181147],
       [ 1.33943298, -0.49481962,  0.59559897,  0.24633692],
       [ 0.37216707, -0.49481962,  0.09298381,  0.10086236],
       [ 0.37216707, -0.94194579,  1.09821414,  0.24633692],
       [ 0.7867096 ,  0.39943271,  0.40711829,  0.39181147],
       [ 0.37216707, -0.49481962,  0.53277208, -0.0446122 ],
       [ 0.92489045, -0.49481962,  0.46994518,  0.39181147],
       [ 0.37216707, -0.27125654,  0.53277208,  0.24633692],
       [-1.28600305,  1.29368504, -1.54051549, -1.64483232],
       [ 0.23398623, -0.

## Choose Algo & set the hyperparameters: 

In [32]:
#lr=LogisticRegression(C=1.0,random_state=0)   #C is Regulararization Parameter
lr=LogisticRegression(C=100,random_state=0)

## Train the Model: 

In [33]:
lr.fit(x_train_std,y_train)

LogisticRegression(C=100, random_state=0)

## Make Prediction using Model:

In [34]:
y_pred=lr.predict(x_test_std)

In [35]:
y_pred

array([2, 1, 0, 2, 0, 2, 0, 1, 1, 1, 2, 1, 1, 1, 1, 0, 1, 1, 0, 0, 2, 1,
       0, 0, 2, 0, 0, 1, 1, 0, 2, 1, 0, 2, 2, 1, 0, 2, 1, 1, 2, 0, 2, 0,
       0, 1, 2, 2, 1, 2, 1, 2, 1, 1, 2, 1, 2, 2, 1, 2, 1, 0, 2, 1, 1, 1,
       1, 2, 0, 0, 2, 1, 0, 0, 1])

In [36]:
print("wrong Predictions out of total:")
print((y_test!=y_pred).sum(),'/',((y_test==y_pred).sum()+y_test!=y_pred).sum())

wrong Predictions out of total:
3 / 75


In [37]:
print('Percentage Accuracy:',100*accuracy_score(y_test,y_pred))

Percentage Accuracy: 96.0


## Confusion matrix: 

In [38]:
from sklearn.metrics import confusion_matrix
cm=confusion_matrix(y_test,y_pred)
cm

array([[21,  0,  0],
       [ 0, 29,  1],
       [ 0,  2, 22]], dtype=int64)

## Missclassified samples:

In [39]:
import numpy as np
np.where(y_pred!=y_test)

(array([37, 48, 55], dtype=int64),)

In [40]:
y_pred[37]

2

In [41]:
y_test[37]

1